import fs from 'node:fs';
import crypto from 'node:crypto';
import { ensureProjectFiles } from './project.js';
import { estimateTokens } from './token-utils.js';

const DEFAULT_MIN_CHARS = 4000;
const DEFAULT_MAX_DIGEST_CHARS = 12000;
const DEFAULT_MAX_DIGEST_LINES = 180;

export function maybeWriteInputDigest(projectRoot = process.cwd(), prompt = '', options = {}) {
  const text = String(prompt || '');
  const minChars = Number(options.minChars || DEFAULT_MIN_CHARS);
  if (text.trim().length < minChars) {
    return { written: false, reason: 'short_prompt', chars: text.length, estimatedTokens: estimateTokens(text) };
  }

  const paths = ensureProjectFiles(projectRoot);
  const digest = buildInputDigest(text, options);
  fs.writeFileSync(paths.inputDigest, digest.content);
  return {
    written: true,
    reason: 'long_prompt_digest_written',
    path: paths.inputDigest,
    chars: text.length,
    estimatedTokens: estimateTokens(text),
    digestChars: digest.content.length,
    digestTokens: estimateTokens(digest.content),
    hash: digest.hash,
    anchors: digest.anchors.length,
    requirements: digest.requirements.length
  };
}

export function buildInputDigest(prompt = '', options = {}) {
  const raw = String(prompt || '').replace(/\r/g, '');
  const hash = shortHash(raw);
  const withoutCodeBlocks = stripLargeCodeBlocks(raw);
  const lines = raw.split(/\n/).map(line => line.trim()).filter(Boolean);
  const plainLines = withoutCodeBlocks.split(/\n/).map(line => line.trim()).filter(Boolean);

  const intent = extractIntent(plainLines);
  const requirements = extractRequirements(plainLines);
  const constraints = extractConstraints(plainLines);
  const decisions = extractDecisions(plainLines);
  const openQuestions = extractOpenQuestions(plainLines);
  const anchors = extractAnchors(raw);
  const commands = extractCommands(raw);
  const files = extractFilePaths(raw);
  const numbers = extractNumbers(raw);
  const warnings = extractWarnings(plainLines);

  let content = `# Long Input Digest

Generated: ${new Date().toISOString()}
Generated by: Token Guard
Source prompt hash: ${hash}

Purpose:
This is a compressed digest of a long user input. It is not a replacement for the user's raw message in the current turn, but it should be used to avoid re-processing or re-summarizing the same wall of text in later turns.

## User Intent

${bulletOrFallback(intent, 'No clear intent extracted. Use the latest user message as source of truth.')}

## Hard Requirements

${bulletOrFallback(requirements, 'No explicit hard requirements extracted.')}

## Constraints / Preferences

${bulletOrFallback(constraints, 'No explicit constraints extracted.')}

## Decisions Already Made

${bulletOrFallback(decisions, 'No explicit decisions extracted.')}

## Open Questions

${bulletOrFallback(openQuestions, 'No explicit open questions extracted.')}

## Important Anchors

### Files / Paths

${bulletOrFallback(files.slice(0, 30), 'No file paths detected.')}

### Commands

${bulletOrFallback(commands.slice(0, 20), 'No commands detected.')}

### Identifiers / Key Terms

${bulletOrFallback(anchors.slice(0, 60), 'No key anchors detected.')}

### Numbers / Thresholds / Versions

${bulletOrFallback(numbers.slice(0, 40), 'No numeric anchors detected.')}

## Risk / Warning Signals

${bulletOrFallback(warnings, 'No explicit risk/warning signals extracted.')}

## Omitted Noise

- Original prompt lines: ${lines.length.toLocaleString('en-US')}
- Original prompt chars: ${raw.length.toLocaleString('en-US')}
- Estimated original tokens: ${estimateTokens(raw).toLocaleString('en-US')}
- Large code blocks / heredocs / repeated long text are intentionally omitted from this digest.
- Preserve exact code, commands, paths, error strings, and identifiers from the raw user message when needed.

## Agent Guidance

- Do not restate the long raw prompt back to the user.
- Use this digest as the working brief for follow-up turns.
- If details are missing or ambiguous, ask a focused question instead of re-processing the entire raw input.
- Keep commands, code, file paths, identifiers, and error messages unchanged.
`;

  content = enforceDigestBudget(content, Number(options.maxChars || DEFAULT_MAX_DIGEST_CHARS), Number(options.maxLines || DEFAULT_MAX_DIGEST_LINES));
  return { content, hash, requirements, constraints, decisions, openQuestions, anchors, commands, files, numbers };
}

function extractIntent(lines) {
  const patterns = [/^(我想|我希望|我要|请|帮我|我们要|我们需要|目标是|核心目标|最终目标)/, /^(i want|i need|please|help me|we need|we want|the goal is|goal:|objective:)/i, /^(ziel|ich möchte|ich will|bitte|hilf mir|wir müssen|wir brauchen)/i];
  return pickLines(lines, patterns, 8, 260).concat(lines.slice(0, 2).map(line => truncate(line, 260))).filter(Boolean).filter(uniqueFilter()).slice(0, 8);
}
function extractRequirements(lines) { return pickLines(lines, [/(必须|一定要|务必|不能|不要|不允许|绝对|必须要|核心要求|要求)/, /\b(must|must not|required|requirement|do not|don't|never|always|should|should not|need to)\b/i, /\b(muss|darf nicht|niemals|immer|soll|sollte|anforderung)\b/i], 16, 260); }
function extractConstraints(lines) { return pickLines(lines, [/(默认|优先|不要默认|本地|不上传|无后台|不能影响|不影响|尽量|只要|除非|安全|可信|体验)/, /\b(default|prefer|local|local-first|no upload|no daemon|safe|trust|unless|avoid|do not block|user experience|ux)\b/i, /\b(standard|bevorzugt|lokal|keine cloud|nicht hochladen|sicher|vertrauen|nutzererlebnis)\b/i], 16, 260); }
function extractDecisions(lines) { return pickLines(lines, [/(决定|确认|已经|我们采用|我们不做|先做|后续|当前版本|最终)/, /\b(decided|confirmed|we will|we won't|we do not|current version|next step|final decision)\b/i, /\b(entschieden|bestätigt|wir werden|wir machen nicht|nächster schritt)\b/i], 12, 260); }
function extractOpenQuestions(lines) { return pickLines(lines, [/[？?]$/, /^(是否|能否|如何|怎么|为什么|要不要|可不可以)/, /^(can|could|should|how|why|whether|what if)\b/i, /^(kann|soll|wie|warum|ob)\b/i], 10, 260); }
function extractWarnings(lines) { return pickLines(lines, [/(风险|注意|警告|危险|不要破坏|不能丢|不能影响|误伤|失败|卡住|复杂|费力)/, /\b(risk|warning|danger|careful|do not break|must not lose|failure|blocked|friction|regression)\b/i, /\b(risiko|warnung|gefahr|vorsicht|nicht kaputt|fehler|blockiert)\b/i], 12, 260); }

function extractCommands(text) {
  const commands = [];
  for (const line of String(text || '').split(/\n/)) {
    const trimmed = line.trim();
    if (/^(npm|pnpm|yarn|node|git|token-guard|tg|python|python3|npx|cd|ls|cat|rg|grep|sed|flutter|gradle|mvn|docker)\b/.test(trimmed)) commands.push(truncate(trimmed, 220));
  }
  return dedupe(commands).slice(0, 30);
}
function extractFilePaths(text) { const re = /(?:\.{0,2}\/)?(?:[A-Za-z0-9_.-]+\/)+[A-Za-z0-9_.-]+\.[A-Za-z0-9]+|(?:TokenGuard|\.token-guard|\.claude)\/[A-Za-z0-9_./-]+|[A-Za-z0-9_.-]+\.(?:js|ts|tsx|jsx|dart|py|java|kt|go|rs|json|md|yaml|yml|toml|xml|html|css|scss|sh|zsh|lock|log)/g; return dedupe(String(text || '').match(re) || []).map(item => item.replace(/[),.;:]+$/g, '')).slice(0, 60); }
function extractNumbers(text) { const re = /(?:v?\d+(?:\.\d+){0,3}(?:-[A-Za-z0-9.]+)?|\d+\s?(?:K|M|tokens?|lines?|chars?|ms|seconds?|minutes?|hours?|days?|%|€|\$)|\d{4}-\d{2}-\d{2})/gi; return dedupe(String(text || '').match(re) || []).map(item => item.trim()).filter(Boolean).slice(0, 50); }
function extractAnchors(text) {
  const anchors = new Set();
  for (const item of String(text || '').match(/`([^`]{2,80})`/g) || []) anchors.add(item.replaceAll('`', '').trim());
  for (const item of String(text || '').match(/\b[A-Za-z_$][A-Za-z0-9_$]*(?:\.[A-Za-z_$][A-Za-z0-9_$]*)+\b|\b[A-Za-z_$][A-Za-z0-9_$]{5,}\b/g) || []) { if (!isLowValueWord(item)) anchors.add(item.trim()); }
  return [...anchors].filter(Boolean).map(item => truncate(item, 100)).slice(0, 80);
}
function pickLines(lines, patterns, limit, maxChars) { const out = []; for (const line of lines) { if (line.length < 3) continue; if (patterns.some(re => re.test(line))) out.push(truncate(line, maxChars)); if (out.length >= limit) break; } return dedupe(out); }
function stripLargeCodeBlocks(text) { return String(text || '').replace(/```[\s\S]*?```/g, '[code block omitted]').replace(/<<\s*['"]?([A-Za-z0-9_-]+)['"]?[\s\S]*?\n\1\b/g, '[heredoc omitted]'); }
function enforceDigestBudget(content, maxChars, maxLines) { let out = String(content || '').trimEnd() + '\n'; const lines = out.split(/\r?\n/); if (lines.length > maxLines) out = lines.slice(0, maxLines).join('\n') + `\n\n[Token Guard: input digest clipped from ${lines.length} to ${maxLines} lines.]\n`; if (out.length > maxChars) out = out.slice(0, maxChars) + `\n\n[Token Guard: input digest clipped to ${maxChars.toLocaleString('en-US')} chars.]\n`; return out; }
function bulletOrFallback(items, fallback = 'None detected.') { const clean = dedupe(items).map(item => String(item || '').trim()).filter(Boolean); if (!clean.length) return fallback; return clean.map(item => `- ${item}`).join('\n'); }
function dedupe(items) { return [...new Set((items || []).filter(Boolean).map(String))]; }
function truncate(text, max) { const s = String(text || '').replace(/\s+/g, ' ').trim(); return s.length <= max ? s : `${s.slice(0, max - 3)}...`; }
function shortHash(text) { return crypto.createHash('sha1').update(String(text || '')).digest('hex').slice(0, 10); }
function uniqueFilter() { const seen = new Set(); return value => { const key = String(value || '').trim(); if (!key || seen.has(key)) return false; seen.add(key); return true; }; }
function isLowValueWord(value) { return new Set(['function', 'return', 'const', 'import', 'export', 'default', 'string', 'number', 'boolean', 'undefined', 'token', 'guard']).has(String(value || '').toLowerCase()); }
